### ISSUE TITLE
Make creation scripts idempotent (repeatable)

### ISSUE THREAD

**Issue by BrentOzar** [olahallengren/sql-server-maintenance-solution#10]
The individual proc/table scripts are all CREATEs, which fail on repeated execution (during development or deployment.) Switch these to if-not-exists-create-a-stub, then alter.

**Comment by BrentOzar** [comment]
(Sorry about that, was trying to close the issues in my personal repo)

**Comment by amtwo** [comment]
I actually surfed over here to suggest this and found Brent beat me to it. Having the scripts be idempotent would make my life a lot easier in making sure that I have the latest version on all my servers.

**Comment by drstonephd** [comment]
Brent, what would you think of adding a extended property for the "Ola" version date on each procedure?  The extended property can be tested so that the alter (or a drop-create) is used only if the existing version is older.  

I plan to use a master job to deploy the maintenance scripts, local jobs, and local schedules.  I'm considering extended properties as a means to avoid making changes unless there is an update.

**Comment by BrentOzar** [comment]
@drstonephd I'd prefer that Ola chimed in on it - since they're his, it'd make the most sense if he picked how he wants it to work.

**Comment by olahallengren** [comment]
Thank you for the request. This is a good idea.

Let's look at the options to implement this:

1. CREATE OR ALTER - Only works on SQL Server 2016 SP1 and later, so that is not an option.

2. Create a stub and then alter - The advantage is that permissions are preserved. The downside is that if for some reason the alter fails, then you are left with the stub.

3. Drop and create - This is what I am using in MaintenanceSolution.sql. That downside is that permissions are not preserved. Not sure how big this issue is.

Drop and create would be a bit easier to implement in my release procedure, as SMO that I am using to script out the objects generates create scripts.

**Comment by drstonephd** [comment]
There is a SMO scripting option that uses a stub.  It seems like it used to use sp_sqlexecute which would have made it possible to use without separate batches.  With separate batches, it's not as easy to use an extended property to skip the code if it's already current.  We could manually wrap it in an execute.  

$scrp = New-Object Microsoft.SqlServer.Management.Smo.Scripter($srv)
$scrp.Options.IncludeIfNotExists = $TRUE
$scrp.Options.ScriptDrops = $FALSE
$scrp.Options.SchemaQualify = $TRUE

The output:

/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4457)
    Source Database Engine Edition : Microsoft SQL Server Standard Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CommandExecute]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[CommandExecute] AS' 
END
ALTER PROCEDURE [dbo].[CommandExecute]

@Command nvarchar(max),
@CommandType nvarchar(max),
...

**Comment by olahallengren** [comment]
IncludeIfNotExists looks like a good option. I will do some testing with this. Thank you.

**Comment by olahallengren** [comment]
I have now changed the scripts, so that they first create a stub, if the stored procedure do not exist, and then alter the stored procedure.

I am using the SMO scripting option IncludeIfNotExists.

**Comment by olahallengren** [comment]
I changed to use IncludeIfNotExists when creating the table. It will then only be created if it does not exist.
