### ISSUE TITLE
“DatabaseIntegrityCheck” procedure to get the results delivered via email

### ISSUE THREAD

**Issue by GithubAriyas** [olahallengren/sql-server-maintenance-solution#115]
Also is it possible to modify the “DatabaseIntegrityCheck” procedure to get the results delivered via email?

**Comment by SQL-Matt** [comment]
I've no connection to Ola but, from my perspective, I would have said "no" because that requires more functionality within the SP to maintain the database mail aspect rather than just the Integrity Check.  The SP is intended to do one task and do it well (which it does).  

A way around this would be to have the output of the step go to a log file and then the next step of the job is a 'mail' step which picks up that file and sends it.  That's not a hard job for a DBA to manage.

I had a similar discussion this morning with one of my team to say that I won't give them all the answers they need to anything - but I will point them in the right direction such that they find the answers for themselves :)

**Comment by olahallengren** [comment]
SQL Server Agent has the ability to send a mail when the job fails or when the job completes.

Unfortunately it does not have an option to include output - files in the mail. Hopefully this can be improved in a later version of SQL Server.

I am not planning add mail sending functionality, to the stored procedures.
