### ISSUE TITLE
"Duplicate" database names cause backup failure

### ISSUE THREAD

**Issue by igorchernysh** [olahallengren/sql-server-maintenance-solution#145]
Hi,

My instance has 2 databases: [ 18752] and [18752]. Backups fail with error:

Msg 50000, Level 16, State 1, Procedure DatabaseBackup, Line 686
The names of the following databases are not unique in the file system: [ 18752], [18752].

Any attempts to separate/exclude those 2 databases in parameter `@Databases` failed.

Thanks,
Igor.

**Comment by olahallengren** [comment]
This is by design.

The reason for that is that, by default I am using the database name as a directory name.

As it is not possible to have a directory name in Windows that starts with a space, I would end up backing up two databases to the same directory.

**Comment by igorchernysh** [comment]
It is definitely possible to have Windows directory/file names with leading spaces:

 

>copy nul "file"

        1 file(s) copied.

 

>copy nul " file"

        1 file(s) copied.

 

>dir *file*

 

2018-09-29  15:49                 0  file

2018-09-29  15:49                 0 file

               2 File(s)              0 bytes

**Comment by srutzky** [comment]
To be clear about the _default_ rules: it is _trialing_ spaces that are not allowed, not _leading_ spaces.

The rules are stated in the "[Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#naming-conventions)" documentation, under "**Naming Conventions**".

For testing:
1. we should test directory names, not file names, since this issue is about directory names,
1. we should use `xp_create_subdir ` since that is what MaintenanceSolution uses, and could possibly be different than doing this directly in a Command Prompt.

```sql
-- Make sure test directory exists:
EXEC [master].dbo.xp_create_subdir N'C:\TEMP';
EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests';

-- Try a varying number of leading spaces:
EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\H';
EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\ H';
EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\  H';
EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\   H';
EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\H  H';
EXEC [master].dbo.xp_dirtree N'C:\TEMP\PathTests';
-- Success (all 5 directories exist)

-- Try both leading and trailing spaces:
EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\   K  ';
EXEC [master].dbo.xp_dirtree N'C:\TEMP\PathTests';
-- Success (kinda)

EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\   K  \L';
/*
Msg 22048, Level 16, State 1, Line XXXXX
xp_create_subdir() returned error 3, 'The system cannot find the path specified.'
*/

EXEC [master].dbo.xp_create_subdir N'C:\TEMP\PathTests\   K\L';
-- Success (trailing spaces were removed from xp_create_subdir N'C:\TEMP\PathTests\   K  ')
EXEC [master].dbo.xp_dirtree N'C:\TEMP\PathTests';


EXEC [master].dbo.xp_cmdshell N'mkdir "C:\TEMP\PathTests\   K  "';
-- A subdirectory or file C:\TEMP\PathTests\   K   already exists.


EXEC [master].dbo.xp_cmdshell N'mkdir "C:\TEMP\PathTests\   K  \L"';
-- The system cannot find the path specified.
```

---

**EXTRA CREDIT**

The reason I emphasized "default" rules at the very top is that, technically, it _is_ possible to create directories with trailing spaces. It just requires using the special `\\?\` syntax (which also allows you to use long paths -- blog post on this coming soon -- but disallows using relative paths).

Continuing the previous examples:

```sql
EXEC [master].dbo.xp_create_subdir N'\\?\C:\TEMP\PathTests\  M  ';
EXEC [master].dbo.xp_create_subdir N'\\?\C:\TEMP\PathTests\  N  \Y';
EXEC [master].dbo.xp_dirtree N'C:\TEMP\PathTests';
-- Success (but you can't really see the trailing spaces when using xp_dirtree)

EXEC [master].dbo.xp_cmdshell N'dir /w C:\TEMP\PathTests';
/*
[.]     [..]    [   H]  [   K]  [  H]   [  M  ] [  N  ] [ H]    [H]     [H  H]
*/

EXEC [master].dbo.xp_cmdshell N'dir /s /b C:\TEMP\PathTests';
/*
C:\TEMP\PathTests\   H
C:\TEMP\PathTests\   K
C:\TEMP\PathTests\  H
C:\TEMP\PathTests\  M  
C:\TEMP\PathTests\  N  
C:\TEMP\PathTests\ H
C:\TEMP\PathTests\H
C:\TEMP\PathTests\H  H
C:\TEMP\PathTests\   K\L
C:\TEMP\PathTests\  N  \Y
*/
```

HOWEVER, the documentation states that _even if you can create directory / file names with trailing spaces, you shouldn't_.

**Comment by SQL-Matt** [comment]
> HOWEVER, the documentation states that even if you can create directory / file names with trailing spaces, you shouldn't.

I agree wholeheartedly with that comment.  I don't want to think about the potential for administrative nightmare that could become when resorting to manual methods for trouble-shooting.
