### ISSUE TITLE
Backup primary Availability Group databases on Secondary Server

### ISSUE THREAD

**Issue by SqlAdmin** [olahallengren/sql-server-maintenance-solution#16]
Hi, I have a SQL Server environment that has one primary and one secondary with auto failover.

Server1 -Primary
Server2 -Secondary 

 I want to create a backup job that should always backup from the primary server.  
l configured this job on Server1, if my AG failover to the another server, the backup is not happening.

So my solution should be like this,

Go and check which is the primary server, then run the backup script against that server. 

or, 

Any ways to directly run this backup script on the listener?

**Comment by Tale-Dejan** [comment]
Hi,
I have same problem how to start job on primary side and...
I resolve with
IF (SELECT ars.role_desc
    FROM sys.dm_hadr_availability_replica_states ars INNER JOIN sys.availability_groups ag
    ON ars.group_id = ag.group_id
    WHERE ag.name = 'Web1' and ars.is_local = 1) = 'PRIMARY'

that is my way to find if DB is on primary server (AlwasyOn).

Maybe it's help to you.

**Comment by atompkins** [comment]
You should have identical jobs setup on both sides.
Ola's backup scripts figure out whether or not it is on the right side for backup.
Depends on the AG backup preference.

**Comment by Tale-Dejan** [comment]
Yes, I have "same" job on both side (with small change).
If I understand you Olla backup script, "see" AG backup preference and start backup on right side?

**Comment by mitch75h** [comment]
Started out with a similar issue, changed the backup preference to the primary. This fixed my backups, but before I made this change, the script failed silently. The fix was not hard, but I think the script should not fail silently when doing a backup in HA and the backup does not meet the config requirements.

**Comment by olahallengren** [comment]
DatabaseBackup has built-in logic for backup of availability groups.

Copy-only full backups and (non copy-only) log backups will always be performed on the preferred backup replica. DatabaseBackup is checking [sys.fn_hadr_backup_is_preferred_replica](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-hadr-backup-is-preferred-replica-transact-sql) (that is based on the [backup preference](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-availability-group-transact-sql) for the availability group). 

Full backups (non copy-only) and differential backups are only supported on the primary replica. DatabaseBackup will always perform these types of backups on the primary replica.

I recommend that you have the jobs configured identically, enabled and scheduled on all replicas. Then it will work automatically after a failover.

**Comment by ChadFrew** [comment]
@olahallengren ... I currently have AG set to Prefer Secondary Replica and have all but DatabaseBackup - USER - DIFF scheduled on both servers: 

Daily at 12:00am - Cleanup - CommandLogs, OutputFiles, sp_delete_backuphistory, sp_purge_jobhistory
Daily at 12:30am - DatabaseIntegrityChecks (SYSTEM and USER)
Daily at 1:00am - IndexOptimize (USER)
Daily at 2:00am - DatabaseBackups (SYSTEM and USER) - FULL

However, based on your statement above regarding copy-only backups... how do I keep TLogs in check? (since copy-only backups don't truncate like full backups do correct?)
https://dba.stackexchange.com/questions/21911/transaction-log-truncation-with-copy-only
The article states "occasionally run full backups on the primary in order to keep your TLogs in check"... How would I go about doing this with your solution?

**Comment by olahallengren** [comment]
If you would like to perform your backups on the secondary replica, then you should have these two backup jobs configured on both servers:

* Copy-only full backups 
* Transaction log backups (non copy-only)

The transaction log backups will take care of truncating the transaction log.

**Comment by ChadFrew** [comment]
Yes @olahallengren, I have those jobs configured on both servers...

'DatabaseBackup - USER - FULL' runs Daily at 2am
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d master -Q "EXECUTE [dbo].[DatabaseBackup] @Databases = 'USER_DATABASES', @Directory = N'G:\Backups', **@BackupType = 'FULL'**, @Verify = 'Y', @CleanupTime = 120, @CheckSum = 'Y', **@CopyOnly = 'Y'**, @LogToTable = 'Y'" -b

'DatabaseBackup - USER - LOG' runs Daily every 2h
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d master -Q "EXECUTE [dbo].[DatabaseBackup] @Databases = 'USER_DATABASES', @Directory = N'G:\Backups', **@BackupType = 'LOG'**, @Verify = 'Y', @CleanupTime = 120, @CheckSum = 'Y', @LogToTable = 'Y'" -b

But database_log files haven't been touched in a month (per modified date of 2/26)... how can I tell they are being truncated? (since as the article above stated, cop-only backups don't truncate logs... but you are saying the LOG backups that run every 2h should take care of truncating the transaction log?)

**Comment by olahallengren** [comment]
Your jobs look good.

Log truncation happens when you back up the transaction log.
https://docs.microsoft.com/en-us/sql/relational-databases/logs/the-transaction-log-sql-server

You are not using (and should not use) the copy-only option for your log backups.

**Comment by ChadFrew** [comment]
OK... so I guess it's just not modifying/shrinking the log file when the TLogs are backed up. Would any of the other jobs conflict with that? (do I have something scheduled wrong that would cause issues?)

![image](https://user-images.githubusercontent.com/37809144/38042001-2bfd4ff8-3281-11e8-8e35-990e20a37cb9.png)

**Comment by olahallengren** [comment]
A transaction log backup does not shrink the transaction log, it only truncates it.

I don't see any issues with your jobs.
