### ISSUE TITLE
PowerShell Version

### ISSUE THREAD

**Issue by Ayanmullick** [olahallengren/sql-server-maintenance-solution#173]
Could there be a PowerShell version of the `MaintenanceSolution.sql` script?

**Comment by dsolodow** [comment]
There is an Install-DbaMaintenanceSolution cmdlet in the dbatools PowerShell module; should accomplish what you need.

**Comment by Ayanmullick** [comment]
@dsolodow Could it be made to work for Azure SQLdb too?

**Comment by dsolodow** [comment]
@Ayanmullick - that's a stickier issue as Azure SQL doesn't have a SQL Agent, so you don't have a good way to run jobs.

**Comment by Ayanmullick** [comment]
@dsolodow, I was hoping there was a PowerShell version that one could schedule to run thru Azure Automation.

**Comment by ConstantineK** [comment]
@Ayanmullick I dont think there's anything stopping you from just calling the stored procedures directly from Azure Automation with powershell, you'd just probably want to tune the execution parameters for the jobs,  - the PowerShell would look something like Invoke-SqlCmd -SqlServer name -Database blah -Query "
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'USER_DATABASES',
@Directory = 'YourPathHere',
@BackupType = 'FULL',
@Verify = 'Y',
@CleanupTime = YourCleanupTimeHere,
@CheckSum = 'Y',
@LogToTable = 'Y'
"

Setting that up as a minimal powershell component isnt a thing you couldnt do, but there's not a ton of value in mapping the hash table for execution of a stored procedure (since each environment is custom when running various parameters.)

**Comment by Ayanmullick** [comment]
I'm an Azure ITPro repurposed to be an SQL admin. I feel I don't know TSQL well enough to convert ~8k lines to PowerShell.

**Comment by ConstantineK** [comment]
Welcome :) and that's not what I am suggesting -  what I recommend is invoking the SQL queries via powershell, so you get the best of both worlds. 

In general I would recommend this approach for a lot of database centric tasks, there's a lot of code around performance tuning, backups, etc which is written in TSQL - you just can call and consume it via PS.

**Comment by Ayanmullick** [comment]
@ConstantineK, But troubleshooting during an issue would be easier if the code was in PowerShell.

**Comment by olahallengren** [comment]
I have currently no plans to make a PowerShell version of the Maintenance Solution.

That said it works well to deploy the scripts through PowerShell or to execute the stored procedures from PowerShell.
