### ISSUE TITLE
Backup master db FULL when ChangeBackupType='Y'

### ISSUE THREAD

**Issue by leepfrog-ger** [olahallengren/sql-server-maintenance-solution#176]
My understanding is that differential backups of `master` are not possible in SQL.
I was under the impression that if you set `ChangeBackupType='Y'` and have a a backup with something along the lines of `@Databases = 'ALL_DATABASES'` then the master DB should be backed up with `FULL` mode, yet it seems to be silently skipped.

I'm not sure if this is intended because I did not find anything regarding this exception in the documentation.

**Comment by olahallengren** [comment]
The ```@ChangeBackupType='Y'``` has been designed to change the backup type only if that will allow you to perform the requested backup type the next time.

Let's look at some examples:

- A database in simple recovery model - ```@BackupType = 'LOG', @ChangeBackupType='Y'``` => The database is skipped 
- A new database in full recovery model - ```@BackupType = 'LOG', @ChangeBackupType='Y'``` => A full backup is performed 
- A new database in full recovery model - ```@BackupType = 'DIFF', @ChangeBackupType='Y'``` => A full backup is performed 
- The master database - ```@BackupType = 'DIFF', @ChangeBackupType='Y'``` => The database is skipped

I will improve the documentation on this.

**Comment by leepfrog-ger** [comment]
Thank you for your feedback and the clarification on this. I understand the design idea behind the flag and why it leads to skipping the DB in my scenario. 

However I am not sure if the result is good from a user perspective. In my case I was switching one environment that used `@Databases = 'ALL_DATABASES'` from daily full to weekly full/daily diff.
My expectation was that with `@ChangeBackupType='Y'` I would be on the safe side and still have a daily backup granularity. Only by chance I noticed `master` was missing. 

My understanding is that I now need to add an additional job with `SYSTEM_DATABASES` (or one explicitly backing up `master`) to ensure I have daily backups of this DB too.

Again I understand why you designed the flag the way it works, I just think other people could make the same mistake as me without noticing (until too late).

**Comment by olahallengren** [comment]
I have been thinking some more about this, and decided to change so that a full backup is triggered, if you perform a differential backup of the [master] database and are using ```@ChangeBackupType='Y'```.
https://ola.hallengren.com/versions.html

**Comment by ilmazzelli** [comment]
Hi Ola, I have a similar problem, I'm in the case of 
A user database in simple recovery model - @BackupType = 'DIFF', @ChangeBackupType='Y' 
A backup DIFF is launched and then I receive following error
Msg 3006, Level 16, State 1, Line 4
The differential backup is not allowed because it would be based on more than one base backup. Multi-based differential backups are not allowed in the simple recovery model, and are never allowed for partial differential backups

If it is important, I've seen that in backupset is_snapshot column equals to 0.

I've set @ChangeBackupType to TRUE thinking to avoid missing of a backup every time I take a DIFF, but in my case it ain't  and I don't understand why
