### ISSUE TITLE
server name is part of file name instead of directory

### ISSUE THREAD

**Issue by Rivanni** [olahallengren/sql-server-maintenance-solution#206]
When I leave the Directory value NULL (default) the server name is part of the backup name like so:
\WINDOWS10VM_MyDatabase_FULL_20190222_125143.bak
 
But when I choose a custom  backup directory the server name becomes a directory.
\WINDOWS10VM\WINDOWS10VM_MyDatabase_FULL_20190222_125143.bak
 
Why isn’t the server name also a directory when I just use the default backup location?

**SQL Server version and edition**
Microsoft SQL Server 2016 (SP2-GDR) (KB4293802) - 13.0.5081.1 (X64) 
	Jul 20 2018 22:12:40 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 17763: ) (Hypervisor)

**Version of the script**
Version: 2019-02-10 10:40:47

**What command are you executing?**

**What output are you getting?**

**Comment by olahallengren** [comment]
This is by design.

The background is that when you are backing up to the instance backup directory (e.g C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup), there is no need to add the server name and instance name (as it will only be that instance backing up to that directory).

However when you specify another directory, the script is adding the server and instance name, as there may be other instances backing up to the same directory.
