### ISSUE TITLE
Error Logging Question, specifically "message column"

### ISSUE THREAD

**Issue by SQLPadre** [olahallengren/sql-server-maintenance-solution#235]
When SQL throws an error on backup commands, shouldn't the error message column be filled with the actual error message?  all I get is 
ErrorNumber: 3013
ErrorMessage: _NULL_
![Capture](https://user-images.githubusercontent.com/3678510/58254335-238f3200-7d30-11e9-912d-ddaa9bc9f6bd.PNG)

**Comment by olahallengren** [comment]
When a backup command fails you get two errors. Here is an example:

Msg 3201, Level 16, State 1, Line 2
Cannot open backup device 'C:\Test.bak'. Operating system error 5(Access is denied.).
Msg 3013, Level 16, State 1, Line 2
BACKUP database is terminating abnormally.

https://blogs.msdn.microsoft.com/sqlprogrammability/2006/04/03/server-side-error-handling-part-2-errors-and-error-messages/

I am executing the backup command without using TRY CATCH. I am using the ```@@ERROR``` variable to get the error number (for the last error). Both errors will be returned in the output - file.

If I would execute the backup command using TRY CATCH, I could get the ERROR_NUMBER() and ERROR_MESSAGE() in the CATCH block, but only for the last error. The problem here is that I would then only be able to return the last error in the output - file.

**Comment by SQLPadre** [comment]
@olahallengren 

I hate to keep harping on this; but I just don't understand the logic. :(

the CommandExecute code below specifically says to update dbo.CommandLog with @ErrorMessageOriginal value; but I think that variable only get value for @Mode =2 (which I have discovered is using TRY CATCH).  Switching to Mode 2 does not help.  
I am not getting ANY error messages from any module, just Error Numbers.  Using a test corrupt database all I get is an Error Number.  not this, which is what would expect in the Error Messages Command Log table.  is it because I am NOT using the master database to house these?  

> Page (1:24473), slot 91 in object ID 421576540, index ID 1, partition ID 72057594039697408, alloc unit ID 72057594044809216 (type "In-row data"). Column "Price" value is out of range for data type "float".  Update column to a legal value.


if we can't have both, how would I change this to be just Error Message and not Number.  numbers are very not informative..  

Is this the testing version of using TRY CATCH? 

```
IF @Mode = 1 AND @Execute = 'Y'
  BEGIN
    EXECUTE @sp_executesql @stmt = @Command
    SET @Error = @@ERROR
    SET @ReturnCode = @Error
  END

  IF @Mode = 2 AND @Execute = 'Y'
  BEGIN
    BEGIN TRY
      EXECUTE @sp_executesql @stmt = @Command
    END TRY
    BEGIN CATCH
      SET @Error = ERROR_NUMBER()
      SET @ErrorMessageOriginal = ERROR_MESSAGE()
      SET @ErrorMessage = 'Msg ' + CAST(ERROR_NUMBER() AS nvarchar) + ', ' + ISNULL(ERROR_MESSAGE(),'')
      SET @Severity = CASE WHEN ERROR_NUMBER() IN(1205,1222) THEN @LockMessageSeverity ELSE 16 END
      RAISERROR('%s',@Severity,1,@ErrorMessage) WITH NOWAIT
      IF NOT (ERROR_NUMBER() IN(1205,1222) AND @LockMessageSeverity = 10)
      BEGIN
        SET @ReturnCode = ERROR_NUMBER()
      END
    END CATCH
  END
........
IF @LogToTable = 'Y'
  BEGIN
    UPDATE dbo.CommandLog
    SET EndTime = @EndTime,
        ErrorNumber = CASE WHEN @Execute = 'N' THEN NULL ELSE @Error END,
        ErrorMessage = @ErrorMessageOriginal
    WHERE ID = @ID
  END
```
