### ISSUE TITLE
Backup to Azure, with compression = Y, is set to NO_COMPRESSION

### ISSUE THREAD

**Issue by gerbowers** [olahallengren/sql-server-maintenance-solution#252]
**Description of the issue**

I execute proc as below.

EXECUTE dbo.DatabaseBackup
@Databases = 'DB',
@URL = 'URL',
@Credential = 'CRED',
@BackupType = 'FULL',
@Compress = 'Y',
@Verify = 'Y'

But execution command is with NO_COMPRESSION

Command: BACKUP DATABASE database TO URL = N'URL'  
WITH NO_CHECKSUM, 
NO_COMPRESSION, 
CREDENTIAL = N''

**SQL Server version and edition**
Execute ```SELECT @@VERSION```

Microsoft SQL Server 2017 (RTM-CU15) (KB4498951) - 14.0.3162.1 (X64)   May 15 2019 19:14:30   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 

**Version of the script**
Check the header of the stored procedure
  --// Version: 2019-06-14 00:05:34   
**What command are you executing?**

EXECUTE dbo.DatabaseBackup
@Databases = 'DB',
@URL = 'URL',
@Credential = 'CRED',
@BackupType = 'FULL',
@Compress = 'Y',
@Verify = 'Y'

**What output are you getting?**
Command: BACKUP DATABASE database TO URL = N'URL'  
WITH NO_CHECKSUM, 
NO_COMPRESSION, 
CREDENTIAL = N''

**Comment by olahallengren** [comment]
I have been doing some testing with this, and I am not able to reproduce it.

Could you please send me a mail with the complete output file.

**Comment by gerbowers** [comment]
Hi,

As requested, and the proc that was run.  Note that we run this from a user database, not from master. But that should not make any difference.

Command Executed:


EXECUTE dbo.DatabaseBackup
@Databases = 'ParcelLocator',
@URL = 'https://ie01svsqdbbackups.blob.core.windows.net/smartship3/',
@Credential = 'ie01svsqdbbackups',
@BackupType = 'FULL',
@Compress = 'Y',
@Verify = 'Y'

Query OutPut:

Date and time: 2019-07-16 12:48:50
Server: IE-01-SV-SQ
Version: 14.0.3162.1
Edition: Enterprise Edition: Core-based Licensing (64-bit)
Platform: Windows
Procedure: [MaintenanceNew].[dbo].[DatabaseBackup]
Parameters: @Databases = 'ParcelLocator', @Directory = NULL, @BackupType = 'FULL', @Verify = 'Y', @CleanupTime = NULL, @CleanupMode = 'AFTER_BACKUP', @Compress = 'Y', @CopyOnly = 'N', @ChangeBackupType = 'N', @BackupSoftware = NULL, @CheckSum = 'N', @BlockSize = NULL, @BufferCount = NULL, @MaxTransferSize = NULL, @NumberOfFiles = NULL, @CompressionLevel = NULL, @Description = NULL, @Threads = NULL, @Throttle = NULL, @Encrypt = 'N', @EncryptionAlgorithm = NULL, @ServerCertificate = NULL, @ServerAsymmetricKey = NULL, @EncryptionKey = NULL, @ReadWriteFileGroups = 'N', @OverrideBackupPreference = 'N', @NoRecovery = 'N', @URL = 'https://ie01svsqdbbackups.blob.core.windows.net/smartship3/', @Credential = 'ie01svsqdbbackups', @MirrorDirectory = NULL, @MirrorCleanupTime = NULL, @MirrorCleanupMode = 'AFTER_BACKUP', @MirrorURL = NULL, @AvailabilityGroups = NULL, @Updateability = 'ALL', @AdaptiveCompression = NULL, @ModificationLevel = NULL, @LogSizeSinceLastLogBackup = NULL, @TimeSinceLastLogBackup = NULL, @DataDomainBoostHost = NULL, @DataDomainBoostUser = NULL, @DataDomainBoostDevicePath = NULL, @DataDomainBoostLockboxPath = NULL, @DirectoryStructure = '{ServerName}${InstanceName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @AvailabilityGroupDirectoryStructure = '{ClusterName}${AvailabilityGroupName}{DirectorySeparator}{DatabaseName}{DirectorySeparator}{BackupType}_{Partial}_{CopyOnly}', @FileName = '{ServerName}${InstanceName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @AvailabilityGroupFileName = '{ClusterName}${AvailabilityGroupName}_{DatabaseName}_{BackupType}_{Partial}_{CopyOnly}_{Year}{Month}{Day}_{Hour}{Minute}{Second}_{FileNumber}.{FileExtension}', @FileExtensionFull = NULL, @FileExtensionDiff = NULL, @FileExtensionLog = NULL, @Init = 'N', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'N', @Execute = 'Y'
Version: 2019-06-14 00:05:34
Source: https://ola.hallengren.com

Date and time: 2019-07-16 12:48:50
Database: [ParcelLocator]
State: ONLINE
Standby: No
Updateability: READ_WRITE
User access: MULTI_USER
Is accessible: Yes
Recovery model: FULL
Encrypted: Yes
Differential base LSN: 58387000000010300095
Last log backup LSN: 58386000000422500001
Allocated extent page count: N/A
Modified extent page count: N/A

Date and time: 2019-07-16 12:48:50
Command: BACKUP DATABASE [ParcelLocator] TO URL = N'https://ie01svsqdbbackups.blob.core.windows.net/smartship3/IE-01-SV-SQ/ParcelLocator/FULL/IE-01-SV-SQ_ParcelLocator_FULL_20190716_124850.bak' WITH NO_CHECKSUM, NO_COMPRESSION, CREDENTIAL = N'ie01svsqdbbackups'
Processed 1338056 pages for database 'ParcelLocator', file 'ParcelLocator' on file 1.
Processed 429 pages for database 'ParcelLocator', file 'ParcelLocator_log' on file 1.
BACKUP DATABASE successfully processed 1338485 pages in 1008.079 seconds (10.373 MB/sec).
Outcome: Succeeded
Duration: 00:16:52
Date and time: 2019-07-16 13:05:42

Date and time: 2019-07-16 13:05:42
Command: RESTORE VERIFYONLY FROM URL = N'https://ie01svsqdbbackups.blob.core.windows.net/smartship3/IE-01-SV-SQ/ParcelLocator/FULL/IE-01-SV-SQ_ParcelLocator_FULL_20190716_124850.bak' WITH NO_CHECKSUM, CREDENTIAL = N'ie01svsqdbbackups'

**Comment by olahallengren** [comment]
It is because the database is encrypted with TDE.

Please see this blog post:
https://blogs.msdn.microsoft.com/sqlcat/2016/06/20/sqlsweet16-episode-1-backup-compression-for-tde-enabled-databases/

You need to specify @MaxTransferSize = 65537, to be able to compress the backup, and in order to do that you also need to switch to a Shared Access Signature.
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2017

**Comment by gerbowers** [comment]
But you can not backup to a URL with MaxTransferSize set, but you can backup to a URL with COMPRESSION.


This;

BACKUP DATABASE [ParcelLocator]
TO URL = N'https://ie01svsqdbbackups.blob.core.windows.net/smartship3/IE-01-SV-SQ_ParcelLocator_FULL_TESTED1.bak'
WITH CHECKSUM,
COMPRESSION,
MAXTRANSFERSIZE = 65537,
CREDENTIAL = N'ie01svsqdbbackups'

Results in this:

Msg 3291, Level 16, State 3, Line 1
URL device type was specified, and a disallowed option MAXTRANSFERSIZE was specified.
Msg 3013, Level 16, State 1, Line 1
BACKUP DATABASE is terminating abnormally.

But this works:
BACKUP DATABASE [ParcelLocator]
TO URL = N'https://ie01svsqdbbackups.blob.core.windows.net/smartship3/IE-01-SV-SQ_ParcelLocator_FULL_TESTED2.bak'
WITH CHECKSUM,
COMPRESSION,
--MAXTRANSFERSIZE = 65537,
CREDENTIAL = N'ie01svsqdbbackups'

Its takes way too long to verify the backup on the URL.


I know you are only look after the SQL Backups, but have you used AZCOPY to copy the backed up db to azure. Would it every be anything you would support as part of the product.

But it painful to get AZCOPY to upload as a page file to blob storage.

Ger

**Comment by olahallengren** [comment]
>But you can not backup to a URL with MaxTransferSize set, but you can backup to a URL with COMPRESSION.

You can back up to URL with COMPRESSION, but you won't get any reduction in size unless you are on SQL Server 2016 and later and set MAXTRANSFERSIZE to a value higher than 65536.

Because of that, I switch to NO_COMPRESSION, if the database is encrypted with TDE, and you have not set MAXTRANSFERSIZE to a value higher than 65536.

To be able to specify MAXTRANSFERSIZE you need to move away from specifying the CREDENTIAL, and use Shared Access Signature instead.

**Comment by bigbird1212** [comment]
I had a similar issue using SQL Server 2017 with TDE databases, my parameters we similar to:
@databases = 'DBname',
@url = 'URL',
@credential = 'CRED',
@BackupType = 'FULL',
@compress = 'Y',
@verify = 'Y'
@MaxTransferSize = 65537

I got an error : "The value for the parameter @MaxTransferSize is not supported."

This is because:
"There are two types of blobs that can be stored in the Microsoft Azure Blob storage service: block and page blobs. SQL Server backup can use either blob type depending upon the Transact-SQL syntax used: If the storage key is used in the credential, page blob will be used; if the Shared Access Signature is used, block blob will be used."
-- If you use parameter @credential = 'CRED' then page blob will be used. Page blob does not support @MaxTransferSize. (Hence my error)
-- With SQL versions 2016 and later you can use a Shared Access Signature (SAS) intead of an Access Key. @credential is not required with SAS. Then @MaxTransferSize is supported. This is the solution to my issue.
Ref:
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2017 


Also note that:
1. SAS are not supported in earlier version than SQL2016 
2. It is not possible to compress backups in SQL 2012/2014 when TDE is enabled. You'll need to upgrade to SQL 2016 or later and set @MaxTransferSize > 65536

**Comment by gerbowers** [comment]
Hi,

Thanks for the reply.
One thing  though, you say “block blob will be used” is this correct, my understanding is that when you restore from a URL then the backup has to be a page blob, so the backup to the URL would have to have been a page blob?

Even when you use a SAS as the key.

Thanks
Gerry

**Comment by olahallengren** [comment]
@gerbowers, please see this:

*******************************************************************************

There are two types of blobs that can be stored in the Microsoft Azure Blob storage service: block and page blobs. SQL Server backup can use either blob type depending upon the Transact-SQL syntax used: If the storage key is used in the credential, page blob will be used; if the Shared Access Signature is used, block blob will be used.

Backup to block blob is only available in SQL Server 2016 or later version. We recommend you to backup to block blob instead of page block if you are running SQL Server 2016 or later version. The main reasons are:

Shared Access Signature is a safer way to authorize blob access compared to storage key.
You can backup to multiple block blobs to get better backup and restore performance, and support larger database backup.
Block blob is cheaper than page blob.

https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2017

*******************************************************************************

**Comment by gerbowers** [comment]
Hi Guys,

I got this working, thanks a lot for the help.

Gerry
