### ISSUE TITLE
Backup:  Error message not logged in dbo.Command table when errornumber is not zero

### ISSUE THREAD

**Issue by Dean-McMillan** [olahallengren/sql-server-maintenance-solution#287]
If the backup could not perform a backup because of insufficient disk space, the error is logged in the table dbo.CommandLog (error 3013) but no error message is populated into the column ErrorMessage.  Is this by design?

Text output from the procedure give the exact issue:

Date and time: 2019-09-09 21:34:11
Command: BACKUP DATABASE [Database1] TO DISK = N'e:\SQLBackups\Database1_FULL\Database1_FULL_20190909_213411.bak' WITH CHECKSUM, COMPRESSION, DESCRIPTION = N'placeholder'
Processed 304 pages for database 'Database1', file 'Database1' on file 1.
Processed 2 pages for database 'Database1', file 'Database1_log' on file 1.
Msg 3202, Level 16, State 1, Line 1
Write on "e:\SQLBackups\Database1_FULL\Database1_FULL_20190909_213411.bak" failed: 112(There is not enough space on the disk.)
Msg 3013, Level 16, State 1, Line 1
BACKUP DATABASE is terminating abnormally.

Should this error message to be written to the CommandLog table? 

**SQL Server version and edition** 
SQL Server Developer Edition (64-bit) 2017 14.0.1000.169, running on Windows 2019 DataCenter (10.0),

**Version of the script**
Version: 2019-06-14 00:05:34   

**What command are you executing?**
BACKUP DATABASE [Database1] TO DISK = N'e:\SQLBackups\Database1_FULL\Database1_FULL_20190909_213411.bak' WITH CHECKSUM, COMPRESSION, DESCRIPTION = N'placeholder'

**What output are you getting?**
Processed 304 pages for database 'Database1', file 'Database1' on file 1.
Processed 2 pages for database 'Database1', file 'Database1_log' on file 1.
Msg 3202, Level 16, State 1, Line 1
Write on "e:\SQLBackups\Database1_FULL\Database1_FULL_20190909_213411.bak" failed: 112(There is not enough space on the disk.)
Msg 3013, Level 16, State 1, Line 1
BACKUP DATABASE is terminating abnormally.

**Comment by olahallengren** [comment]
This is because of a limitation in SQL Server.

The BACKUP DATABASE command outputs [two errors](https://blogs.msdn.microsoft.com/sqlprogrammability/2006/04/03/server-side-error-handling-part-2-errors-and-error-messages/). When you are using TRY CATCH you can only catch the second error using the ERROR_MESSAGE() function.

Because of that I am not using TRY CATCH for the BACKUP DATABASE command. This way both errors are output to the output - file.

For the logging to table, I am using the ```@@ERROR``` variable for the BACKUP DATABASE command.
