### ISSUE TITLE
when getting Hallengren version:::   OBJECT_DEFINITION() returns null

### ISSUE THREAD

**Issue by duanelawrence** [olahallengren/sql-server-maintenance-solution#293]
I am SA and OBJECT_DEFINITION() returns null.  Microsoft says that it is because I don't have permission.  I changed the query to use sys.sql_modules.  I value how much this open source has helped my career and I would be honored if I can give back.

SELECT oo.[object_id]
      ,ss.[name] AS SchemaName
      ,oo.[name] AS ObjectName
      ,CASE WHEN CHARINDEX(@VersionKeyword,mm.[definition]) > 0 
            THEN SUBSTRING(mm.[definition],CHARINDEX(@VersionKeyword,mm.[definition]) + LEN(@VersionKeyword) +1, 19) END AS [Version]
      ,CAST(CHECKSUM(CAST(mm.[definition] AS nvarchar(max)) COLLATE SQL_Latin1_General_CP1_CI_AS) AS bigint) AS [Checksum]
FROM [master].sys.objects as oo
JOIN [master].sys.schemas as ss ON oo.[schema_id] = ss.[schema_id]
JOIN [master].sys.sql_modules as mm on mm.[object_id] = oo.[object_id]
WHERE ss.[name] = 'dbo'
AND oo.[name] IN('CommandExecute','DatabaseBackup','DatabaseIntegrityCheck','IndexOptimize')
ORDER BY ss.[name] ASC, oo.[name] ASC

**Comment by olahallengren** [comment]
Could you try this?

```SELECT OBJECT_DEFINITION(OBJECT_ID('dbo.DatabaseBackup'))```

**Comment by Rob-S** [comment]
@duanelawrence Was OBJECT_DEFINITION returning null in SQL Server Management studio, or _only_ when it was run as an agent job? We had an instance where it was returning null only when running as a job (along with other anomalies, such as not backing up all the DBs). It appeared to be some kind of permissions issue, but the SQL Server Agent service account has the sysadmin role and OBJECT_DEFINITION returns the definition just fine when logged into SSMS as that account. It was only one of the backup jobs on this one instance, with the only difference being Full/Diff/Log, and in an almost identical instance, including the service account, permissions, and job options, everything works OK. It turned out that somehow, the "Run as user" option in the Advanced settings of the Job Step had gotten set (to the same user as the SQL Server Agent service account). Apparently that causes it to ignore the fact that the Login has the sysadmin role.

To recreate the issue with OBJECT_DEFINITION returning null despite the job being owned by "sa", set the "Run as user" in the job step to a user which has the sysadmin role and permission to one or more of the user databases, but not to the master database where the DatabaseBackup stored procedure resides.
