### ISSUE TITLE
MaintenanceSolution default values

### ISSUE THREAD

**Issue by LBegnaud** [olahallengren/sql-server-maintenance-solution#60]
Are you willing to take input on the default values for this solution? It seems like the purpose of this `.sql` file is to make a simple install that fits most cases. I would say that for the SQL Agent jobs for backups, it would make more sense to have a non-NULL value for `CleanupTime` and a NULL value for `Directory`

Also perhaps injecting some standard schedules (not applied to any of the jobs) would be helpful such as 

- Daily 7pm
- Hourly 1h
- Weekly Saturday 6pm
- etc

(but that's perhaps going a bit out of scope)

**Comment by olahallengren** [comment]
All input are welcome. I created MaintenanceSolution.sql to make it easy for people to get started with the solution. About the defaults:

CleanupTime: I have been thinking that I should not delete any backups by default. I would like the user to set the cleanup time.

Directory: It could make sense to use NULL here. Then it would back up to the SQL Server default backup directory. My concern has been that if the user has not configured the default backup directory, it would back up to something like "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Backup", and then the user can't find the backup files (and it could fill up the drive).

Scheduling: I prefer to let the user schedule the jobs, so that he or she has to do something actively for things to start running. It would also be difficult for me to define the schedules as different organizations have different maintenance windows.

**Comment by LBegnaud** [comment]
Thanks for the reply.

- That's fair on the cleanuptime. 
- Per the directory that seems like a small inconvenience, and honestly at least it would run the backup. If C:\Backup doesn't exist, the jobs will fail. Seems like a cleaner choice to use the instance defaults.
- I was more suggesting to create some standard schedule objects, not to apply them to the jobs. I do like that the agent jobs create unscheduled.

**Comment by olahallengren** [comment]
Thank you for the feedback. I am leaning towards changing the default for the directory to NULL (instance default).

**Comment by LBegnaud** [comment]
Thanks.

Also thank you in general for this amazing resource.

**Comment by olahallengren** [comment]
I have changed the backup directory now.
https://ola.hallengren.com/versions.html

I am not planning to do anything with schedules.

**Comment by OliverUweHahn** [comment]
This is great!!! Just realised that the BackupDirectory defaults now to NULL.
Hurray!!!
Thank you!
