### ISSUE TITLE
Why Binary choices have (n)varchar(max) on DatabaseBackup parameters?

### ISSUE THREAD

**Issue by SysDaemon** [olahallengren/sql-server-maintenance-solution#751]
**Declaring a variable with maximum space, when the choices are binary**

Hence, the choices will be "Y" or "N", why declare nvarchar(**max**) on these parameters?

**Comment by olahallengren** [comment]
This was a decision long time ago and then I have followed this standard.

Here are some of the arguments as I recall them:

- "Y" or "N" is more easy to understand than a bit column with 1 and 0.
- For other string parameters (e.g., BackupType) using a non-max length could be a source of bugs, as the strings are automatically truncated. Because of that I standardized parameters and variables to nvarchar(max), and that also included the "Y" or "N" parameters.

It could be argued that a bit column is a more natural choice for the "Y" or "N".
